# Generated by Django 3.0.2 on 2020-03-09 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('bying_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_price', models.IntegerField()),
            ],
        ),
    ]
