# Generated by Django 3.0.2 on 2020-03-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='bying_price',
        ),
        migrations.AddField(
            model_name='bond',
            name='buying_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='bond',
            name='total_price',
            field=models.IntegerField(default=0),
        ),
    ]
