# Generated by Django 3.0.2 on 2020-03-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20200309_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='buying_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bond',
            name='total_price',
            field=models.IntegerField(),
        ),
    ]
