# Generated by Django 3.0.2 on 2020-04-08 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20200326_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bond',
            name='buying_price',
        ),
        migrations.RemoveField(
            model_name='bond',
            name='total_price',
        ),
    ]
